CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR NOT NULL
);

CREATE TABLE users_roles (
    user_id bigint REFERENCES users(id) NOT NULL,
    role_id bigint REFERENCES roles(id) NOT NULL,
    PRIMARY KEY(user_id, role_id)
);

INSERT INTO roles (name) VALUES('ROLE_ADMIN');
INSERT INTO roles (name) VALUES('ROLE_USER');